{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aleth-lite-explorer.serviceAccountName" . }}
  labels:
{{ include "aleth-lite-explorer.labels" . | nindent 4 }}
{{- end -}}
